name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: [cron: "42 1 * * *"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: cargo test

  wasm-pack:
    name: Test (wasm)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable && rustup default stable
    - name: Run wasm-pack tests
      run: |
        cargo install --git https://github.com/rustwasm/wasm-pack.git
        wasm-pack test --node

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --all-features -- -Dclippy::all -Dclippy::pedantic